import React, { useEffect, useRef } from "react";
import * as echarts from "echarts";
import "echarts-wordcloud";
import carMask from "../../../assets/images/wordcloud.png"; // Make sure this path is correct

const NotificationScreen = () => {
  return (
    <div className="h-screen w-screen snap-start">
      <div>Title</div>
      <WordCloud data={data} maskImage={carMask}></WordCloud>
      <div>Notification</div>
    </div>
  );
};

export default NotificationScreen;

const data = [
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
  { name: "JavaScript", value: 1000 },
  { name: "TypeScript", value: 800 },
  { name: "React", value: 600 },
  { name: "Vue", value: 400 },
];

const WordCloud = ({ data, maskImage }: any) => {
  const chartRef = useRef(null);

  useEffect(() => {
    const chart = echarts.init(chartRef.current);

    const maskImg = new Image();
    maskImg.src = maskImage; // Use the imported mask image

    maskImg.onload = function () {
      const option = {
        series: [
          {
            type: "wordCloud",
            gridSize: 8,
            sizeRange: [12, 60],
            rotationRange: [0, 0],
            shape: "circle",
            maskImage: maskImg,
            textStyle: {
              normal: {
                color: function () {
                  return (
                    "rgb(" +
                    [
                      Math.round(Math.random() * 255),
                      Math.round(Math.random() * 255),
                      Math.round(Math.random() * 255),
                    ].join(",") +
                    ")"
                  );
                },
              },
            },
            data: data,
          },
        ],
      };

      chart.setOption(option);
    };

    return () => {
      chart.dispose();
    };
  }, [data]);

  return (
    <div ref={chartRef} style={{ width: "1500px", height: "600px" }}></div>
  );
};
